//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace PdfiumOverlayTest.Localization
{
    [CompilerGenerated]
    internal class Strings
    {
        private static ResourceManager? resourceMan;
        private static CultureInfo? resourceCulture;

        internal Strings()
        {
        }

        internal static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    ResourceManager temp = new ResourceManager("TestPDFViewer.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        internal static CultureInfo? Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static string StartForm_Title
        {
            get
            {
                return ResourceManager.GetString("StartForm_Title", resourceCulture) ?? "Kürzel für PDF-Dateien";
            }
        }

        internal static string Button_SetTags
        {
            get
            {
                return ResourceManager.GetString("Button_SetTags", resourceCulture) ?? "Tag setzen (PDF öffnen)";
            }
        }

        internal static string Button_ManageCategories
        {
            get
            {
                return ResourceManager.GetString("Button_ManageCategories", resourceCulture) ?? "Kategorien (Tags) verwalten";
            }
        }

        internal static string Button_CompanyData
        {
            get
            {
                return ResourceManager.GetString("Button_CompanyData", resourceCulture) ?? "Firmen-/Personendaten";
            }
        }

        internal static string Button_Exit
        {
            get
            {
                return ResourceManager.GetString("Button_Exit", resourceCulture) ?? "Beenden";
            }
        }

        internal static string Message_CompanyDataSaved
        {
            get
            {
                return ResourceManager.GetString("Message_CompanyDataSaved", resourceCulture) ?? "Firmendaten wurden erfolgreich gespeichert.";
            }
        }

        internal static string Message_Success
        {
            get
            {
                return ResourceManager.GetString("Message_Success", resourceCulture) ?? "Erfolg";
            }
        }

        internal static string Error_LoadCompanyData
        {
            get
            {
                return ResourceManager.GetString("Error_LoadCompanyData", resourceCulture) ?? "Fehler beim Laden der Firmendaten:";
            }
        }

        internal static string Error_SaveCompanyData
        {
            get
            {
                return ResourceManager.GetString("Error_SaveCompanyData", resourceCulture) ?? "Fehler beim Speichern der Firmendaten:";
            }
        }

        internal static string Error_Title
        {
            get
            {
                return ResourceManager.GetString("Error_Title", resourceCulture) ?? "Fehler";
            }
        }

        internal static string Message_LanguageChanged
        {
            get
            {
                return ResourceManager.GetString("Message_LanguageChanged", resourceCulture) ?? "Sprache wurde geändert. Einige Änderungen werden beim nächsten Start wirksam.";
            }
        }
    }
}
